In [ ]:
    # Machine Learning Approach
    #The machine learning approach starts with either a problem that you need to solve or a given dataset that you need to ananlyze.

In [ ]:
# 1) Understand the problem/dataset.
#2) Extract the features from the dataset.
#3)Identify the problem type.
#4) Choose the right model.
#5) Train and test the models.
#6) Strive for accuracy.

In [ ]:
# Scikit Learn ---- Problem-Solution Considerations
#While working with Scikit Learn dataset or loading your data to Scikit Learn, always consider these four points 
#mentioned here:
#1) Create separate objects for features and response.
#2) Ensure that features and response have only numeric values.
#3) Features and response should be in the form of NumPy ndarray.
#4) Since features and response would be in the form of arrays , they would have shapes and sizes.
#5)Features are always marked as X, response is mapped as Y.

In [ ]:
# y=mx +c --------> Simple Linear equation

In [ ]:
#Linear regression in Scikit-Learn.
# sklearn.linear_model.LinearRegression(fit_intercept=True,normalize=False,copy_X=True,n_jobs=1)
#fit_intercept -----> Calculates the intercept for this model.
# normalize ---- > Normalizes the regression variable before performing the regression operation.
# copy_X ------> Copies the regression variable.
# n_jobs -----> Number of jobs to use for the computation.

In [1]:
# Machine learning -- Load and explore dataset.
import numpy as np
import pandas as pd

In [3]:
#import Scikit-Learn dataset
from sklearn.datasets import load_boston
boston_dataset=load_boston()

In [4]:
print (boston_dataset['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
#print the features of the dataset
print (boston_dataset['feature_names'])

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [7]:
#Store data into a dataframe 
df_boston=pd.DataFrame(boston_dataset.data)

In [8]:
#set features as columns on the dataframe
df_boston.columns=boston_dataset.feature_names

In [9]:
#view first 5 observations
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [10]:
#print dataset matrix(observations and features matrix)
print (boston_dataset.data.shape)

(506, 13)


In [11]:
# print dataset target or response shape
print (boston_dataset.target.shape)

(506,)


In [12]:
#view targets or response
print (boston_dataset['target'])

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [13]:
# Machine Learning - Linear Regression demo
# import required libraries
import numpy as np
import pandas as pd
import sklearn

In [14]:
# import the boston dataset
from sklearn.datasets import load_boston
boston_dataset=load_boston()

In [15]:
# Create a pandas dataframe and store the data
df_boston=pd.DataFrame(boston_dataset.data)
df_boston.columns=boston_dataset.feature_names

In [17]:
#append Price , Target as a new column to the dataset
df_boston['Price']=boston_dataset.target

In [18]:
# print top 5 observations
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [19]:
#assign features on X axis
X_features=boston_dataset.data

In [20]:
# assign target on Y axis
Y_target= boston_dataset.target

In [26]:
# import Linear model - the estimator 
from sklearn.linear_model import LinearRegression
lineReg=LinearRegression()

In [29]:
#fit data into the estimator
lineReg.fit(X_features,Y_target)

LinearRegression()

In [28]:
# print the intercept
print ('the estimated intercept %.2f '%lineReg.intercept_)

the estimated intercept 36.46 


In [24]:
# print the coefficient
print ('the coefficient is %d' %len(lineReg.coef_))

the coefficient is 13


In [33]:
# train model split the whole dataset into train and test datasets
#from sklearn import cross_validation --- depreceted
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train , Y_test = train_test_split(X_features,Y_target)

In [6]:
conda update conda

Note: you may need to restart the kernel to use updated packages.
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\USER\anaconda3

  added / updated specs:
    - conda



The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backports.functools_lru_cache-1.6.4|     pyhd3eb1b0_0           9 KB
    backports.tempfile-1.0     |     pyhd3eb1b0_1          11 KB
    conda-4.10.3               |   py38haa95532_0         2.9 MB
    conda-package-handling-1.7.3|   py38h8cc25b3_1         721 KB
    xmltodict-0.12.0           |     pyhd3eb1b0_0          13 KB
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following packages will be UPDATED:

  backports.functoo~                             1.6.1-py_0 --> 1.6.4-pyhd3eb1b0_0
  conda                                4.9.2-py38ha

conda-4.10.3         | 2.9 MB    | #########2 |  93% 
conda-4.10.3         | 2.9 MB    | #########3 |  93% 
conda-4.10.3         | 2.9 MB    | #########3 |  94% 
conda-4.10.3         | 2.9 MB    | #########4 |  94% 
conda-4.10.3         | 2.9 MB    | #########4 |  95% 
conda-4.10.3         | 2.9 MB    | #########5 |  95% 
conda-4.10.3         | 2.9 MB    | #########5 |  96% 
conda-4.10.3         | 2.9 MB    | #########6 |  96% 
conda-4.10.3         | 2.9 MB    | #########6 |  97% 
conda-4.10.3         | 2.9 MB    | #########7 |  97% 
conda-4.10.3         | 2.9 MB    | #########8 |  98% 
conda-4.10.3         | 2.9 MB    | #########8 |  99% 
conda-4.10.3         | 2.9 MB    | #########9 |  99% 
conda-4.10.3         | 2.9 MB    | #########9 | 100% 
conda-4.10.3         | 2.9 MB    | ########## | 100% 
conda-4.10.3         | 2.9 MB    | ########## | 100% 

backports.tempfile-1 | 11 KB     |            |   0% 
backports.tempfile-1 | 11 KB     | ########## | 100% 
backports.tempfile-1 | 11 K

In [35]:
#Print the dataset shape
print (boston_dataset.data.shape)

(506, 13)


In [36]:
#Print shapes of the training and testing datasets
print (X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(379, 13) (127, 13) (379,) (127,)


In [37]:
#Fit the training sets into the model
lineReg.fit(X_train,Y_train)

LinearRegression()

In [42]:
# The mean square error (MSE) or residual sum of squares
print ('MSE value is %.2f '% np.mean((lineReg.predict(X_test)-Y_test) ** 2))

MSE value is 41.02 


In [43]:
#Calculate Variance ---- Closer the value is to 1 higher the model's accuracy.
print('Variance score is %.2f '% lineReg.score(X_test,Y_test))

Variance score is 0.62 


In [ ]:
              # Supervised Learning Models : Logistic Regression
    #Logistic regression is a generalization of the linear regression model , used for classification problems. 

In [ ]:
# class sklearn.linear_model.LogisticRegression(penalty=l2,fit_intercept=True,dual=False,C=1.0,n_jobs=1,warm_start=False)
# Penalty-- Specifies the norm used in penalization .
# dual=False -- Implemented only for L2 penalty
#C =1.0 ---- Inverse of regularization
#warm_start --- If true , reuse the solution of the previous call.
#n_jobs=1 --- Number of jobs in parallel computation.
# random_state = None --- Seed or the random state instance .


In [ ]:
# Supervised Learning Models : K Nearest Neighbors (K_NN) 
# K-nearest neighbors, or K-NN, is one of the simplest machine learning algorithms used for both classification and regression
# problem types.

In [6]:
#import necessary library
import numpy as np
import pandas as pd

In [7]:
#import sklearn Load dataset
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [8]:
# display the dataset type
type(iris_dataset)

sklearn.utils.Bunch

In [9]:
#view information using dataset built in method DESCR (describe)
print(iris_dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [10]:
#view features
print (iris_dataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [11]:
# view target (response)
print (iris_dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
# find number of observations
print (iris_dataset.data.shape)

(150, 4)


In [14]:
#Assign features data to X axis
X_feature=iris_dataset.data

In [15]:
# Assign target data to Y axis
Y_target=iris_dataset.target

In [16]:
# View the shape for both axes.
print (X_feature.shape)
print (Y_target.shape)

(150, 4)
(150,)


In [17]:
# first use KNN classifier method - import it from sklearn ---- to find out the nearest neighbours of the datapoint for a given value of K.
from sklearn.neighbors import KNeighborsClassifier

In [18]:
# instantiate the KNN estimator-- The object used to instantiate the class of a learning model is called an estimator.
knn=KNeighborsClassifier(n_neighbors=1) # pass the K neighbor value as 1 so that estimator will look for the first nearest neighbor.

In [19]:
# print the knn
print (knn)

KNeighborsClassifier(n_neighbors=1)


In [20]:
# fit data into KNN model (estimator)
knn.fit(X_feature,Y_target)

KNeighborsClassifier(n_neighbors=1)

In [21]:
# create object with new values for prediction
X_new=[[3,5,4,1],[5,3,4,2]]

In [22]:
# predict the outcome for the new observation using knn classifier 
knn.predict(X_new)

array([1, 1])

In [42]:
# use the logistic regression estimator
from sklearn.linear_model import LogisticRegression
#logReg=LogisticRegression(random_state=0,multi_class='multinomial',penalty='none',solver='newton-cg')
logReg=LogisticRegression(random_state=None,multi_class='ovr',solver='liblinear')
#logReg=LogisticRegression(random_state='none',solver='newton-cg',multi_class='ovr',penalty='none',max_iter=1000)

In [61]:
# Print the params
params=logReg.get_params()
print (params)

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'multinomial', 'n_jobs': None, 'penalty': 'none', 'random_state': 0, 'solver': 'newton-cg', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [43]:
# fit data into the logistic regression estimator
logReg.fit(X_feature,Y_target)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [44]:
# predict the outcome using the Logistic Regression estimator
logReg.predict(X_new)

array([0, 2])

In [ ]:
#Unsupervised Learning Models: K-Means Clustering
# A cluster is a group of similar data points.
#It is used:
# To extract the structure of the data.
# To identify groups in the data.

In [ ]:
#K-means finds the best centroids by alternatively assigning random centroids to a dataset and selecting mean data points
# from the resulting clusters to form new centroids . It  continues this process iteratively until the model is optimised. 

In [ ]:
# sklearn.cluster.KMeans(n_clusters=8,init='k-means++',n_init=10,max_iter=300,tol=0.0001,precompute_distances='auto',verbose=0,random_state=none,copy_x=True,n_jobs=1)

In [3]:
# import required libraries
import numpy as np

# import KMeans class from sklearn.cluster
from sklearn.cluster import KMeans

# import make_blobs dataset from sklearn.cluster
from sklearn.datasets import make_blobs

In [4]:
#define number of samples
n_samples=300
#define random state value to initialize the center
random_state=20
# define the number of feature as 5 
X,y=make_blobs(n_samples=n_samples,n_features=5,random_state=None)
#define the number of cluster to be formed as 3 and in random state and fit features into the model
predict_y=KMeans(n_clusters=3,random_state=random_state).fit_predict(X)
#print the estimator prediction
predict_y

array([1, 1, 2, 1, 1, 0, 2, 2, 0, 2, 1, 1, 1, 1, 0, 2, 1, 0, 0, 2, 2, 2,
       2, 2, 2, 1, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 2, 0, 1, 1,
       2, 0, 1, 2, 1, 0, 2, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 2, 2,
       0, 1, 2, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 2, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 2, 2, 2,
       2, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 2, 2,
       1, 0, 2, 1, 2, 1, 1, 2, 2, 2, 1, 0, 1, 1, 1, 2, 0, 0, 2, 0, 2, 2,
       2, 1, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 1, 0, 1, 0, 0, 0, 1, 1, 2, 1,
       1, 0, 0, 2, 1, 1, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 0, 2, 2, 2, 0, 2,
       1, 0, 2, 2, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 1, 2, 2, 0, 0, 2, 2, 1,
       2, 0, 1, 1, 0, 2, 1, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0,
       0, 2, 2, 2, 0, 1, 2, 0, 2, 0, 2, 1, 0, 0, 2, 0, 1, 1, 1, 2, 1, 1,
       0, 1, 0, 2, 1, 1, 0, 2, 1, 1, 0, 1, 1, 2, 1, 1, 2, 1, 1, 0, 0, 0,
       1, 2, 2, 2, 2, 1, 1, 1, 0, 0, 0, 0, 2, 2])

In [ ]:
#Unsupervised Learning Models: Dimensionality Reduction
# It reduces a high-dimensional dataset into a dataset with fewer dimensions.This makes it easier and faster for the algorithm to analyse the data.

In [ ]:
# Techniques used for dimensionality reduction:
# 1) Drop data columns with missing values.
# 2) Drop data columns with low variance.
# 3) Drop data columns with high correlations.
# 4) Apply statistical functions - (PCA)Principal Component Analysis

In [ ]:
# Unsupervised Learning Models : Principal Component Analysis (PCA)
# It is a linear dimensionality reduction method which uses singular value decomposition of the data and keeps only the
#most significant singular vectors to project the data to a lower dimensional space.

#1) It is primarily used to compress or reduce the data.
#2) PCA tries to capture the variance , which helps it pick up interesting features.
#3) PCA is used to reduce dimensionality in the dataset and to build our feature vector.
#4) Here , the principal axis in the feature space represents the direction of mazimum variance in the data. 

In [ ]:
# sklearn.decomposition.PCA(n_components=None,copy=True,whiten=False)
#sklearn -- class
#n_components -- Number of components to keep
# copy= True -- Overwrites the transform data after fitting them into the model
# whiten=False ---- Removes data with low variance 

In [1]:
#  import required library PCA
from sklearn.decomposition import PCA 
# import the dataset
from sklearn.datasets import make_blobs

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
#define sample and random state
n_sample=20
random_state=20

In [3]:
# Generate the dataset with 10 features (dimension)
X,y=make_blobs(n_samples=n_sample,n_features=10,random_state=None)

In [4]:
#view the shape of the dataset.
X.shape

(20, 10)

In [5]:
#define the PCA estimator with number of reduced components
pca=PCA(n_components=3)

In [6]:
# fit the data into the PCA estimator
pca.fit(X)
print (pca.explained_variance_ratio_)

[0.67060479 0.31024151 0.0058942 ]


In [7]:
# print the first PCA component
first_pca=pca.components_[0]
print (first_pca)

[ 0.16883296  0.21332105 -0.44409182  0.41640712  0.45829818  0.25090813
  0.14881592 -0.2534976  -0.20074121 -0.39456403]


In [8]:
# transform the fitted data using transform method.
pca_reduced=pca.transform(X)

In [9]:
# view the reduced shape (lower dimension)
pca_reduced.shape

(20, 3)

In [ ]:
# PIPELINE 
#Pipeline is mainly used to combine multiple models or estimators .Its characteristics are as follows:
#1) It simplifies the process where more than one model is required or used.
#2) Once all the data is fit into the models or estimators , the predict method can be called.
#3) All models in the pipeline must be transformers. The last model can either be a transformer or a classifier, regressor,
# , or other such objects.

In [21]:
# Estimators are known as 'Model instance'
# import pipeline class
from sklearn.pipeline import Pipeline

# import Linear estimatorestimator=[('dim_reductioestimator=[('dim_reduction',PCA(),('linear_model',LinearRegression())]n',PCA(),('linear_model',LinearRegression())]
from sklearn.linear_model import LinearRegression

# import PCA estimator for dimensionality reduction
from sklearn.decomposition import PCA

In [5]:
# Chain the estimators together
estimator=[('dim_reduction',PCA()),('linear_model',LinearRegression())]

In [7]:
#Put the chain of estimators in a pipeline object
pipeline_estimator=Pipeline(estimator)

In [8]:
# Check the chain of estimators
pipeline_estimator

Pipeline(steps=[('dim_reduction', PCA()), ('linear_model', LinearRegression())])

In [9]:
# View first step
pipeline_estimator.steps[0]

('dim_reduction', PCA())

In [10]:
# View second step
pipeline_estimator.steps[1]

('linear_model', LinearRegression())

In [11]:
#View all the steps in pipeline
pipeline_estimator.steps

[('dim_reduction', PCA()), ('linear_model', LinearRegression())]

In [ ]:
  # Model Persistence
  #  Save model for future use . No need to retrain your model every time you need them.
# 1) It is possible to save a model by using Python's Pickle model.
 #2) Scikit-learn has a special replacement for Pickle called joblib.
# 3) You can use joblib.dump and joblib.load methods.
# 4) These are more efficient for Big Data.

In [4]:
# import required Libraries and dataset
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [5]:
# View feature names of the dataset.
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
# View target of the dataset
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
#define features and target objects.
X_feature=iris_dataset.data
Y_target=iris_dataset.target

In [9]:
# create object with new values for prediction.
X_new=[[3,5,4,1],[5,3,4,2]]

In [12]:
# Use the Logistic regression estimator
from sklearn.linear_model import LogisticRegression
#logreg=LogisticRegression(random_state=0,multi_class='multinomial',penalty='none',solver='newton-cg')
logreg=LogisticRegression(random_state=None,multi_class='ovr',solver='liblinear')

In [13]:
# fit data into the Logistic regression estimator.
logreg.fit(X_feature,Y_target)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [14]:
# predict the outcome using Logistic regression estimator.
logreg.predict(X_new)

array([0, 2])

In [16]:
# import library for model persistence
import pickle as pkl

In [17]:
# use dumps method to persist the model
persist_model=pkl.dumps(logreg)
persist_model

b"\x80\x04\x95)\x03\x00\x00\x00\x00\x00\x00\x8c\x1esklearn.linear_model._logistic\x94\x8c\x12LogisticRegression\x94\x93\x94)\x81\x94}\x94(\x8c\x07penalty\x94\x8c\x02l2\x94\x8c\x04dual\x94\x89\x8c\x03tol\x94G?\x1a6\xe2\xeb\x1cC-\x8c\x01C\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\rfit_intercept\x94\x88\x8c\x11intercept_scaling\x94K\x01\x8c\x0cclass_weight\x94N\x8c\x0crandom_state\x94N\x8c\x06solver\x94\x8c\tliblinear\x94\x8c\x08max_iter\x94Kd\x8c\x0bmulti_class\x94\x8c\x03ovr\x94\x8c\x07verbose\x94K\x00\x8c\nwarm_start\x94\x89\x8c\x06n_jobs\x94N\x8c\x08l1_ratio\x94N\x8c\x0en_features_in_\x94K\x04\x8c\x08classes_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x1c\x8c\x05dtype\x94\x93\x94\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x0c\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x94t\x94b\x8c\x05coef_\x94h\x

In [33]:
# use joblib.dump to persist the model to a file.
#from sklearn.externals import joblib
#from sklearn.externals import joblib
import joblib
joblib.dump(logreg,'regresfilename.pk1')

['regresfilename.pk1']

In [34]:
#use joblib.Load to persist the model to a file
# Create new estimator from the saved model
new_logreg_estimator=joblib.load('regresfilename.pk1')

In [35]:
#View the new estimator
new_logreg_estimator

LogisticRegression(multi_class='ovr', solver='liblinear')

In [36]:
# validate and use new estimator to predict
new_logreg_estimator.predict(X_new)

array([0, 2])

In [ ]:
# Model Evaluation : Metric Functions
#You can use the "Metrics" function to evaluate the accuracy of your model's predictions.
# Classification --> metrics.accuracy_score & metrics.average_precision_score
# Clustering  ----> metrics.adjusted_rand_score
#Regression  ------> metrics.mean_absolute_error , metrics.mean_squared_error, metrics.median_absolute_error
