In [1]:
import sys
print(sys.version)

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


In [3]:
import platform
print(platform.version)

<function version at 0x00000034ABCE7550>


In [4]:
platform.python_version()

'3.8.5'

In [5]:
8*4

32

In [2]:
x=3

In [3]:
type(x)

int

In [4]:
z='test'

In [5]:
type(z)

str

In [6]:
num_x=none

NameError: name 'none' is not defined

In [7]:
num_x=None

In [8]:
num_x is None

True

In [9]:
num_x=10

In [10]:
num_x is None

False

In [11]:
float_number=3.6467

In [12]:
float_number

3.6467

In [13]:
int(float_number)

3

In [14]:
str(float_number)

'3.6467'

In [15]:
first_tuple=(12,'Jack',45.6,(3,2),'test')

In [16]:
first_tuple

(12, 'Jack', 45.6, (3, 2), 'test')

In [17]:
first_tuple[1]

'Jack'

In [18]:
first_tuple[1]='Samir'

TypeError: 'tuple' object does not support item assignment

In [19]:
first_tuple[2]

45.6

In [20]:
first_tuple[-3]

45.6

In [21]:
first_tuple

(12, 'Jack', 45.6, (3, 2), 'test')

In [22]:
first_tuple[1:4]

('Jack', 45.6, (3, 2))

In [23]:
first_tuple[1:-1]

('Jack', 45.6, (3, 2))

In [24]:
first_list=['Mark',101,23.6,'test',None,11]

In [25]:
first_list

['Mark', 101, 23.6, 'test', None, 11]

In [26]:
print(first_list)

['Mark', 101, 23.6, 'test', None, 11]


In [27]:
first_list.append('Samir')

In [28]:
first_list

['Mark', 101, 23.6, 'test', None, 11, 'Samir']

In [29]:
first_list.remove('Mark')

In [30]:
first_list

[101, 23.6, 'test', None, 11, 'Samir']

In [31]:
first_list.pop(2)

'test'

In [32]:
first_list.insert(1,'Smith')

In [33]:
first_list

[101, 'Smith', 23.6, None, 11, 'Samir']

In [34]:
first_list[2]

23.6

In [35]:
first_list[-2]

11

In [36]:
first_list

[101, 'Smith', 23.6, None, 11, 'Samir']

In [37]:
first_list[1:4]

['Smith', 23.6, None]

In [38]:
first_list[1:-1]

['Smith', 23.6, None, 11]

In [39]:
first_dict={'John':'john@abc.com','Kelly':'kelly@xyz.org','id':[23,81]}

In [40]:
first_dict

{'John': 'john@abc.com', 'Kelly': 'kelly@xyz.org', 'id': [23, 81]}

In [41]:
first_dict.keys()

dict_keys(['John', 'Kelly', 'id'])

In [42]:
first_dict.type()

AttributeError: 'dict' object has no attribute 'type'

In [43]:
type(first_dict)

dict

In [44]:
type(first_tuple)

tuple

In [45]:
type(first_list)

list

In [46]:
first_dict.values()

dict_values(['john@abc.com', 'kelly@xyz.org', [23, 81]])

In [47]:
first_dict['Kelly']

'kelly@xyz.org'

In [48]:
first_dict['id']

[23, 81]

In [49]:
first_dict

{'John': 'john@abc.com', 'Kelly': 'kelly@xyz.org', 'id': [23, 81]}

In [50]:
first_dict.update({'id':[32,55]})

In [51]:
first_dict

{'John': 'john@abc.com', 'Kelly': 'kelly@xyz.org', 'id': [32, 55]}

In [53]:
del first_dict['id']

KeyError: 'id'

In [54]:
del first_dict['id']

KeyError: 'id'

In [55]:
first_dict

{'John': 'john@abc.com', 'Kelly': 'kelly@xyz.org'}

In [56]:
first_list

[101, 'Smith', 23.6, None, 11, 'Samir']

In [57]:
first_list.remove(3)

ValueError: list.remove(x): x not in list

In [58]:
first_list.remove[3]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [59]:
first_list.insert(2,99.9)

In [60]:
first_list

[101, 'Smith', 99.9, 23.6, None, 11, 'Samir']

In [61]:
first_list.pop(-1)

'Samir'

In [62]:
first_list

[101, 'Smith', 99.9, 23.6, None, 11]

In [63]:
auto_survey_set={'Audi','BMW','BMW','Ferrari','GM','Mercedes','Chevrolet','GM'}

In [64]:
type(auto_survey_set)

set

In [65]:
auto_survey_set

{'Audi', 'BMW', 'Chevrolet', 'Ferrari', 'GM', 'Mercedes'}

In [66]:
auto_survey_1={'Audi','BMW','BMW','Ferrari','GM','Mercedes','Chevrolet','GM','Toyota'}
auto_survey_2={'BMW','Ferrari','GM','Hyundai','Kia','Chevrolet','GM','Ford','Toyota','Zen'}

In [67]:
type(auto_survey_1)

set

In [68]:
type(auto_survey_2)

set

In [69]:
combined_survey_report=auto_survey_1|auto_survey_2

In [70]:
combined_survey_report

{'Audi',
 'BMW',
 'Chevrolet',
 'Ferrari',
 'Ford',
 'GM',
 'Hyundai',
 'Kia',
 'Mercedes',
 'Toyota',
 'Zen'}

In [71]:
combined_survey_report=auto_survey_1&auto_survey_2

In [72]:
combined_survey_report

{'BMW', 'Chevrolet', 'Ferrari', 'GM', 'Toyota'}

In [73]:
'BMW' in combined_survey_report

True

In [74]:
'Nano' in combined_survey_report

False

In [75]:
word='encyclopedia'

In [76]:
't' in word

False

In [77]:
'i' in word

True

In [78]:
first_name='George'

In [79]:
last_name='Washington'

In [80]:
full_name=first_name+last_name

In [81]:
full_name

'GeorgeWashington'

In [82]:
full_name=first_name+' '+last_name

In [83]:
full_name

'George Washington'

In [84]:
test_score_1=(68,96,71)
test_score_2=(92,87,83)

In [85]:
test_score=test_score_1+test_score_2
test_score

(68, 96, 71, 92, 87, 83)

In [86]:
name='friend'*3
name

'friendfriendfriend'

In [87]:
age=(12,17,9)*3

In [88]:
age

(12, 17, 9, 12, 17, 9, 12, 17, 9)

In [89]:
id=[103,23,77,45] * 2
id

[103, 23, 77, 45, 103, 23, 77, 45]

In [90]:
def my_first_function(name):
    return name

In [91]:
print (my_first_function('Jack'))

Jack


In [92]:
def my_first_function(name):

SyntaxError: unexpected EOF while parsing (<ipython-input-92-05d4ab470e39>, line 1)

In [93]:
def my_first_function(name):
return

IndentationError: expected an indented block (<ipython-input-93-a551e5471096>, line 2)

In [94]:
def my_first_function(name):
    return

In [95]:
print (my_first_function('Jack'))

None


In [96]:
def add_two_numbers(num1,num2):
    return num1 + num2

In [97]:
result=add_two_numbers(146,238)
result

384

In [98]:
def profile():
    age=21
    height=5.5
    weight=130
    return age , height, weight
age , height,weight=profile()

In [99]:
print age , height, weight

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(age , height, weight)? (<ipython-input-99-1807423d3868>, line 1)

In [100]:
print (age , height, weight)

21 5.5 130


In [1]:
def profile():
    age=21
    height=5.5
    weight=130
    return age , height, weight

In [2]:
age_x,height_x,weight_x=profile()
print (age_x,height_x,weight_x)

21 5.5 130


In [3]:
store_list=['McDonnald','Taco Bell','Dunkin','Wendys','Chipotle']

In [5]:
for position,name in enumerate (store_list):
    print (position,name)

0 McDonnald
1 Taco Bell
2 Dunkin
3 Wendys
4 Chipotle


In [6]:
for x,y in enumerate (store_list):
    print (x,y)

0 McDonnald
1 Taco Bell
2 Dunkin
3 Wendys
4 Chipotle


In [7]:
store_map=dict((name,position) for name,position in enumerate (store_list))

In [8]:
store_map

{0: 'McDonnald', 1: 'Taco Bell', 2: 'Dunkin', 3: 'Wendys', 4: 'Chipotle'}

In [9]:
store_map.values()

dict_values(['McDonnald', 'Taco Bell', 'Dunkin', 'Wendys', 'Chipotle'])

In [10]:
type(store_map)

dict

In [11]:
sorted([91,43,65,56,7,33,21])

[7, 21, 33, 43, 56, 65, 91]

In [12]:
sorted ('the data science')

[' ',
 ' ',
 'a',
 'a',
 'c',
 'c',
 'd',
 'e',
 'e',
 'e',
 'h',
 'i',
 'n',
 's',
 't',
 't']

In [13]:
num_list=range(20)

In [14]:
num_list

range(0, 20)

In [15]:
rev=reversed (num_list)

In [16]:
rev

In [17]:
list(reversed (num_list))

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [18]:
print(num_list)

range(0, 20)


In [19]:
list(num_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [20]:
string('Samir Banerjee')

NameError: name 'string' is not defined

In [21]:
str_1='Samir Banerjee'

In [22]:
str_1

'Samir Banerjee'

In [23]:
reversed (str_1)

In [26]:
def palin (str_1):
    my_str=str_1.casefold()
    rev_str=reversed(my_str)
    if list(my_str)==list(rev_str):
        print ("The String is Palindrome")
    else:
        print ("The string is not Palindrome")

In [27]:
str_2=palin('Samir')

The string is not Palindrome


In [28]:
str_2=palin('radar')

The String is Palindrome


In [29]:
str_2=palin('madam')

The String is Palindrome


In [30]:
def str_func1 (str_1):
    my_str=str_1.casefold()
    print (list(my_str))

In [31]:
str_3=str_func1('Samir')

['s', 'a', 'm', 'i', 'r']


In [32]:
subjects=['math','statistics','algebra']
subject_count=['one','two','three']

In [33]:
total_subject=zip(subjects,subject_count)
total_subject

In [34]:
total_subject

In [35]:
type(total_subject)

zip

In [36]:
print (total_subject)

In [38]:
list(total_subject)

[('math', 'one'), ('statistics', 'two'), ('algebra', 'three')]

In [39]:
type(list(total_subject))

list

In [1]:
stock_tickers=['AAPL','MSFT','GOOGL',None,'AMZN','CSCO','ORCL']

In [2]:
for tickers in (stock_tickers):
    if (tickers is None):
        continue
        print tickers

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(tickers)? (<ipython-input-2-a5b13d3b31bf>, line 4)

In [4]:
for tickers in (stock_tickers):
    if (tickers is None):
        continue
   print (tickers)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [5]:
for tickers in (stock_tickers):
    if (tickers is None):
        continue
    print (tickers)

AAPL
MSFT
GOOGL
AMZN
CSCO
ORCL


In [6]:
for tickers in (stock_tickers):
    if (tickers is None):
          break
    print (tickers)

AAPL
MSFT
GOOGL


In [7]:
def test_float(number):
    return float(number)

In [8]:
test_float(7.32453)

7.32453

In [9]:
test_float('test float')

ValueError: could not convert string to float: 'test float'

In [10]:
def test_float(number):
    try:
    return float(number)
except ValueError:
    return 'not a number , the input value is', number

IndentationError: expected an indented block (<ipython-input-10-8fcfa02236ed>, line 3)

In [1]:
age=21

In [5]:
if age<18:
    print ('Minor')
else:
    print ('Adult')
        

Adult


In [6]:
marks=81

In [7]:
if marks>90:
    print ('grade A')
elif 80<=marks<=90:
    print ('grade B')
elif 70<=marks<=80:
    print ('grade C') 
elif 60<=marks<=70:
    print ('grade D')
else:
    print ('grade F')


grade B


In [10]:
def test_float(number):
    try:
         return float(number)
    except ValueError:
         return 'not a number , the input value is', number

In [11]:
test_float('Test')

('not a number , the input value is', 'Test')

In [12]:
test_float(999.8)

999.8

In [13]:
test_float(999)

999.0

In [14]:
#Introducing Numpy

In [4]:
distance=[10,15,17,26]
time=[.30,.47,.55,1.20]
speed=distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
import numpy as np
np_distance=np.array(distance)
np_time=np.array(time)
speed=np_distance/np_time

In [6]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [20]:
first_numpy_array=np.array([1,2,3,4])

In [21]:
print (first_numpy_array)

[1 2 3 4]


In [22]:
array_with_zeros=np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
array_with_ones=np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
array_with_empty=np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#one dimesional array

np_arrange=np.arange(12)
print(np_arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
# two dimensional array
np_arrange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# three dimesional array
ThreeD_array=np.arange(27).reshape(3,3,3)

In [10]:
print (ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [7]:
#To findout dimesions of the array
np_city=np.array(['NYC','LA','Miami','Houston'])

In [8]:
np_city.ndim

1

In [9]:
np_city_with_state=np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','Texas']])

np_city_with_state.ndim

In [10]:
np_city_with_state.ndim

2

In [11]:
#Indicate the size along each dimesion
np_city.shape

(4,)

In [12]:
np_city_with_state.ndim

2

In [13]:
np_city_with_state.shape

(2, 4)

In [14]:
np_city.size

4

In [15]:
np_city_with_state.size

8

In [16]:
np_city_with_state.dtype

dtype('<U7')

In [17]:
first_trial_cyclist=[10,15,27,26]

In [19]:
second_trial_cyclist=[12,11,21,24]

In [20]:
np_first_trial_cyclist=np.array(first_trial_cyclist)

In [21]:
np_second_trial_cyclist=np.array(second_trial_cyclist)

In [22]:
np_first_trial_cyclist+np_second_trial_cyclist

array([22, 26, 48, 50])

In [23]:
np.add(45,26)

71

In [24]:
np.subtract(90,45)

45

In [25]:
np_daily_wage=np.array([7,9,13,8,11]) * 15

In [26]:
print (np_daily_wage)

[105 135 195 120 165]


In [27]:
sum(np_daily_wage)

720

In [28]:
np_weekly_hrs=np.array([23,41,55,47,38])

In [29]:
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [30]:
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

In [31]:
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [4]:
# To view the axis 0 and axis 1 data
cyclist_trials=np.array([[10,15,17,26],[12,11,21,24]])

In [5]:
first_trial=cyclist_trials[0]

In [6]:
first_trial

array([10, 15, 17, 26])

In [7]:
second_trial=cyclist_trials[1]

In [8]:
second_trial

array([12, 11, 21, 24])

In [9]:
first_cyclist_firstTrial=cyclist_trials[0][0]

In [10]:
first_cyclist_firstTrial

10

In [11]:
first_cyclist_allTrials=cyclist_trials[:,0]

In [12]:
first_cyclist_allTrials

array([10, 12])

In [13]:
cyclist_trials.shape

(2, 4)

In [15]:
#Slicing the array
two_cyclist_trail_data=cyclist_trials[:,1:3]

In [16]:
two_cyclist_trail_data

array([[15, 17],
       [11, 21]])

In [17]:
for x in cyclist_trials:
    print (x)

[10 15 17 26]
[12 11 21 24]


In [18]:
for y in two_cyclist_trail_data:

SyntaxError: unexpected EOF while parsing (<ipython-input-18-d261c35bde72>, line 1)

In [19]:
for y in two_cyclist_trail_data:
    print(y)

[15 17]
[11 21]


In [21]:
test_scores=np.array([[83,71,57,63],[54,68,81,45]])

In [23]:
passing_score=test_scores>60

In [24]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [27]:
test_scores(passing_score)

TypeError: 'numpy.ndarray' object is not callable

In [28]:
#Array copy and views
NYC_Borough=np.array(['Manhattan','Bronx','Brroklyn','Staten Island','Queens'])

In [29]:
#Original Dataset
NYC_Borough

array(['Manhattan', 'Bronx', 'Brroklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [30]:
Boroughs_in_NYC=NYC_Borough

In [31]:
# Assigned Dataset
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brroklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [32]:
Boroughs_in_NYC is NYC_Borough

True

In [33]:
#Shallow copy or View
View_of_borough_in_NYC=Boroughs_in_NYC.view()

In [34]:
len(View_of_borough_in_NYC)

5

In [35]:
View_of_borough_in_NYC[4]='Central Park'#Change value in 'view' object

In [36]:
View_of_borough_in_NYC

array(['Manhattan', 'Bronx', 'Brroklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [37]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brroklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [38]:
#Deep copy
Copy_of_NYC_Borough=NYC_Borough.copy()

In [39]:
Copy_of_NYC_Borough is NYC_Borough  # Copy and original object are different.

False

In [40]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brroklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [41]:
Copy_of_NYC_Borough[4]='Queens'

In [42]:
Copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brroklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [43]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brroklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [44]:
#Universal functions in Numpy (Ufunc)
np_sqrt=np.sqrt([2,4,9,16])

In [45]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [46]:
from numpy import pi
np.cos(0)

1.0

In [47]:
np.sin(pi/2)

1.0

In [48]:
np.cos(pi)

-1.0

In [49]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [51]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [52]:
# Shape Manipulation
np_cyclist_trials=np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [53]:
np_cyclist_trials.ravel() # Flatten the dataset

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [54]:
np_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [55]:
np_cyclist_trials.resize(2,6)

In [56]:
np_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [58]:
np.hsplit(np_cyclist_trials,2)  # Split the array into two.

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [59]:
new_cyclist_1=np.array([10,15,17,26,13,19])

In [60]:
new_cyclist_2=np.array([12,11,21,24,14,23])

In [62]:
np.hstack((new_cyclist_1,new_cyclist_2))     # Stack the arrays together

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [63]:
import numpy as np

In [64]:
    #Create two arrays of the same shape
    array_a=np.array([2,3,5,8])
    array_b=np.array([.3,.3,.3,.3])

In [65]:
#Multiply arrays
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [66]:
#Create a variable with scalar value
scalar_c=.3

In [67]:
#Multiply 1D array with a scalar value
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

In [70]:
np_week_one=np.array([105,135,195,120,165]) # Week one earnings

In [68]:
np_week_two=np.array([123,156,230,200,147])  #Week two earnings

In [71]:
total_earnings=np_week_one + np_week_two # Total earnings for two weeks

In [72]:
total_earnings

array([228, 291, 425, 320, 312])

In [75]:
np_week_one_hrs=np_week_one/15 #Calculate weekly one hours

In [76]:
np_week_one_hrs         # Number of working hours per day in week one

array([ 7.,  9., 13.,  8., 11.])

In [7]:
#Linear Algebra -- Transpose-- Converting rows into columns and vice versa
test_scores=np.array([[83,71,57,63],[54,68,81,45]])

In [8]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [9]:
# Linear Algebra -- Inverse and trace functions -- can be applied only on square matrix.
inverse_array=np.array([[10,20],[15,25]])

In [10]:
np.linalg.inv(inverse_array) # Inverse of the given array

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [11]:
trace_array=np.array([[10,20],[22,31]])

In [12]:
np.trace(trace_array)# Sum of diagonal 10 and 31

41

In [6]:
# GDP of Countries
import numpy as np

In [7]:
list_of_countries=np.array(['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'
])

In [16]:
list_of_countries

array(['Algeria', 'Angola', 'Argentina', 'Australia', 'Austria',
       'Bahamas', 'Bangladesh', 'Belarus', 'Belgium', 'Bhutan', 'Brazil',
       'Bulgaria', 'Cambodia', 'Cameroon', 'Chile', 'China', 'Colombia',
       'Cyprus', 'Denmark', 'El Salvador', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Georgia', 'Ghana', 'Grenada', 'Guinea',
       'Haiti', 'Honduras', 'Hungary', 'India', 'Indonesia', 'Ireland',
       'Italy', 'Japan', 'Kenya', 'South Korea', 'Liberia', 'Malaysia',
       'Mexico', 'Morocco', 'Nepal', 'New Zealand', 'Norway', 'Pakistan',
       'Peru', 'Qatar', 'Russia', 'Singapore', 'South Africa', 'Spain',
       'Sweden', 'Switzerland', 'Thailand', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Venezuela',
       'Vietnam', 'Zimbabwe'], dtype='<U20')

In [8]:
GDP=np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])

In [18]:
GDP

array([ 2255.225482 ,   629.9553062, 11601.63022  , 25306.82494  ,
       27266.40335  , 19466.99052  ,   588.3691778,  2890.345675 ,
       24733.62696  ,  1445.760002 ,  4803.398244 ,  2618.876037 ,
         590.4521124,   665.7982328,  7122.938458 ,  2639.54156  ,
        3362.4656   , 15378.16704  , 30860.12808  ,  2579.115607 ,
        6525.541272 ,   229.6769525,  2242.689259 , 27570.4852   ,
       23016.84778  ,  1334.646773 ,   402.6953275,  6047.200797 ,
         394.1156638,   385.5793827,  1414.072488 ,  5745.981529 ,
         837.7464011,  1206.991065 , 27715.52837  , 18937.24998  ,
       39578.07441  ,   478.2194906, 16684.21278  ,   279.2204061,
        5345.213415 ,  6288.25324  ,  1908.304416 ,   274.8728621,
       14646.42094  , 40034.85063  ,   672.1547506,  3359.517402 ,
       36152.66676  ,  3054.727742 , 33529.83052  ,  3825.093781 ,
       15428.32098  , 33630.24604  , 39170.41371  ,  2699.123242 ,
       21058.43643  , 28272.40661  , 37691.02733  ,  9581.0565

In [26]:
def max_GDP (countries,Gross):
    max_ind=Gross.argmax()
    max_country=countries[max_ind]
    max_GDP=Gross[max_ind]
    return(max_country,max_GDP)

In [25]:
maximum_GDP=max_GDP(list_of_countries,GDP)
print (maximum_GDP)

('Norway', 40034.85063)


In [30]:
def min_GDP(countries,Gross):
    min_ind=Gross.argmin()
    min_country=countries[min_ind]
    min_GDP=Gross[min_ind]
    return(min_country,min_GDP)

In [31]:
minimum_GDP=min_GDP(list_of_countries,GDP)
print (minimum_GDP)

('Ethiopia', 229.6769525)


In [17]:
countries_list=['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe']

In [18]:
countries_list

['Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Bahamas',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Bhutan',
 'Brazil',
 'Bulgaria',
 'Cambodia',
 'Cameroon',
 'Chile',
 'China',
 'Colombia',
 'Cyprus',
 'Denmark',
 'El Salvador',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Georgia',
 'Ghana',
 'Grenada',
 'Guinea',
 'Haiti',
 'Honduras',
 'Hungary',
 'India',
 'Indonesia',
 'Ireland',
 'Italy',
 'Japan',
 'Kenya',
 'South Korea',
 'Liberia',
 'Malaysia',
 'Mexico',
 'Morocco',
 'Nepal',
 'New Zealand',
 'Norway',
 'Pakistan',
 'Peru',
 'Qatar',
 'Russia',
 'Singapore',
 'South Africa',
 'Spain',
 'Sweden',
 'Switzerland',
 'Thailand',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Venezuela',
 'Vietnam',
 'Zimbabwe']

In [20]:
gdp_list=[2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605]

In [30]:
total_gdp=zip(countries_list,gdp_list)  #list of countries along with their GDPs
list(total_gdp)

[('Algeria', 2255.225482),
 ('Angola', 629.9553062),
 ('Argentina', 11601.63022),
 ('Australia', 25306.82494),
 ('Austria', 27266.40335),
 ('Bahamas', 19466.99052),
 ('Bangladesh', 588.3691778),
 ('Belarus', 2890.345675),
 ('Belgium', 24733.62696),
 ('Bhutan', 1445.760002),
 ('Brazil', 4803.398244),
 ('Bulgaria', 2618.876037),
 ('Cambodia', 590.4521124),
 ('Cameroon', 665.7982328),
 ('Chile', 7122.938458),
 ('China', 2639.54156),
 ('Colombia', 3362.4656),
 ('Cyprus', 15378.16704),
 ('Denmark', 30860.12808),
 ('El Salvador', 2579.115607),
 ('Estonia', 6525.541272),
 ('Ethiopia', 229.6769525),
 ('Fiji', 2242.689259),
 ('Finland', 27570.4852),
 ('France', 23016.84778),
 ('Georgia', 1334.646773),
 ('Ghana', 402.6953275),
 ('Grenada', 6047.200797),
 ('Guinea', 394.1156638),
 ('Haiti', 385.5793827),
 ('Honduras', 1414.072488),
 ('Hungary', 5745.981529),
 ('India', 837.7464011),
 ('Indonesia', 1206.991065),
 ('Ireland', 27715.52837),
 ('Italy', 18937.24998),
 ('Japan', 39578.07441),
 ('Kenya'

In [13]:
#Highest GDP
def GDP_highest (Gross):
    highest=Gross.argmax()
    highest_gdp=Gross[highest]
    return (highest_gdp)

In [17]:
GDP_max=GDP_highest(GDP)
print ("Highest GDP",GDP_max)

Highest GDP 40034.85063


In [18]:
#Lowest GDP
def GDP_lowest (Gross):
    lowest=Gross.argmin()
    lowest_gdp=Gross[lowest]
    return (lowest_gdp)

In [19]:
GDP_min=GDP_lowest(GDP)
print ("Lowest GDP",GDP_min)

Lowest GDP 229.6769525


In [21]:
#Sum of all GDPS
Sum_of=np.sum(GDP)
print ("Sum of all GDPs--", Sum_of)

Sum of all GDPs-- 711232.7841133


In [22]:
#Mean GDP value
Mean_of=np.mean(GDP)
print ("Mean GDP value--", Mean_of)

Mean GDP value-- 11289.409271639683


In [23]:
#Standardized GDP value
Std_of=np.std(GDP)
print ("GDP Standard deviation--",Std_of)

GDP Standard deviation-- 12743.828910617945


In [1]:
#London Olympics dataset
import numpy as np
np_olympic_country=np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_gold=np.array([29,38,24,46,13,7,11])
np_olympic_silver=np.array([17,28,25,28,8,14,11])
np_olympic_bronze=np.array([19,22,32,29,7,17,14])

In [2]:
#Countrywith max gold medals
max_gold_index=np_olympic_gold.argmax()
country_with_max_gold=np_olympic_country[max_gold_index]

In [3]:
print (country_with_max_gold)

US


In [4]:
#Countries with more than 20 gold medals
print (np_olympic_country[np_olympic_gold>20])

['GBR' 'China' 'RUS' 'US']


In [7]:
#print each country name with number of gold medals
#print each country with total number of medals
for i in range (len(np_olympic_country)):
    gold_medal=np_olympic_gold[i]
    country=np_olympic_country[i]
    total_medal=np_olympic_gold[i]+ np_olympic_silver[i] + np_olympic_bronze[i]
    print ('{}, gold medal {}, Total medals {}'.format(country,gold_medal,total_medal))

GBR, gold medal 29, Total medals 65
China, gold medal 38, Total medals 88
RUS, gold medal 24, Total medals 81
US, gold medal 46, Total medals 103
KOR, gold medal 13, Total medals 28
JPN, gold medal 7, Total medals 38
GER, gold medal 11, Total medals 36
