In [ ]:
# Scipy extension of Numpy.

In [1]:
from scipy.integrate import quad

In [5]:
def integrateFunction(x):
    return x

In [6]:
quad(integrateFunction,0,1) # Perform quad integration for fucntion of x for limit 0 to 1.

(0.5, 5.551115123125783e-15)

In [7]:
def integrateFn(x,a,b): # Define function for ax+b
    return x*a+b

In [8]:
a=3 # Declare value of a and b.
b=2

In [10]:
quad(integrateFn,0,1,args=(a,b)) # Perform quad integration

(3.5, 3.885780586188048e-14)

In [12]:
# Perform multiple integration
import scipy.integrate as integrate # import integrate sub package.
def f (x,y):
    return x + y
integrate.dblquad(f,0,1,lambda x:0, lambda x: 2)

(3.0, 4.436070580899685e-14)

In [ ]:
# Optimization is the process to improve performance of a system mathematically by fine tuning the process parameters
# Scipy provides several several optimization algorithms such as bfgs , Nelder-Mead simplex , Newton Conjugate gradient, COBYLA or SLSQP.


In [13]:
# import numpy and optimize from scipy.
import numpy as np
from scipy import optimize

In [14]:
def f(x):
    return x**2 + 5*np.sin(x) # Define function for X^2+5 sinx

In [15]:
minimavalue = optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [16]:
minimaValueWithoutOpt=optimize.minimize(f,x0=2,method='bfgs')

In [17]:
minimaValueWithoutOpt

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [18]:
import numpy as np
from scipy.optimize import root
def rootfunc(x):                 # define function for x + 3.5 cos x
    return x + 3.5 * np.cos(x)

In [19]:
rootValue=root(rootfunc, 0.3)

In [20]:
rootValue

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

In [21]:
import numpy as np
from scipy import linalg  # import linalg and define an numpy matrix or array.
matrix=np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [22]:
type(matrix)

numpy.ndarray

In [23]:
linalg.inv(matrix) # Use inv function to inverse the matrix.

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [25]:
# Finding determinant
#Compute the value of the determinant for the given matrix.
import numpy
from scipy import linalg
matrix= np.array ([[4,9],[3,5]])
matrix

array([[4, 9],
       [3, 5]])

In [26]:
linalg.det(matrix)

-7.000000000000001

In [ ]:
# Linear equation
# 2x + 3y + z= 21
# -x + 5y + 4z= 9
# 3x + 2y + 9z=6

In [27]:
import numpy as np
from scipy import linalg

In [28]:
numArray= np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [30]:
numArrValue=np.array([21,9,6])

In [31]:
linalg.solve(numArray,numArrValue)

array([ 4.95,  4.35, -1.95])

In [32]:
# Linear algebra capabilities and contains algebraic functions.
import numpy as np
from scipy import linalg

In [33]:
# Single value decomposition (svd)
numSvdArr= np.array([[3,5,1],[9,5,7]])

In [34]:
numSvdArr.shape

(2, 3)

In [35]:
linalg.svd(numSvdArr) # Use SVD function.

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))